name: First Workflow
on: workflow_dispatch
jobs: 
  first_job: 
    runs-on: ubuntu-latest
    steps: 
     - name: afficher OpenCart
       run: echo "salut"
     - name: fermer OpenCart
       run: echo "Fin"
